replicaCount: 1

image:
    repository: vvelc/nb-api-proto
    tag: "latest"
    pullPolicy: IfNotPresent

service:
    type: NodePort
    port: 80

ingress:
    enabled: false
    host: "localhost"

resources:
    limits:
        cpu: 100m
        memory: 128Mi
    requests:
        cpu: 100m
        memory: 128Mi

autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

server:
  ingress:
    enabled: true
    hosts:
      - argocd.local
    paths: ["/"]
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /

nodeSelector: {}

tolerations: []

affinity: {}
