replicaCount: 1

image:
    repository: vvelc/nb-api-proto
    tag: "latest"
    pullPolicy: IfNotPresent

service:
    type: ClusterIP
    port: 80

ingress:
    enabled: false
    host: "localhost"

resources:
    limits:
        cpu: 100m
        memory: 128Mi
    requests:
        cpu: 100m
        memory: 128Mi

autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
