replicaCount: 5
image:
    repository: vvelc/nb-api-proto
    tag: "main-latest"
    pullPolicy: Always

service:
    type: ClusterIP
    port: 80

ingress:
    enabled: false
    host: "prod.127.0.0.1.nip.io"
