apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: nb-api-proto-prod
    namespace: argocd
spec:
    project: default
    source:
        repoURL: "https://github.com/vvelc/nb-api-proto-infra"
        targetRevision: HEAD
        path: "charts/nb-api-proto"
        helm:
            valueFiles:
                - values-prod.yaml
    destination:
        server: "https://kubernetes.default.svc"
        namespace: production
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
        - CreateNamespace=true
