apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: nb-api-proto-prod
    namespace: argocd
spec:
    project: default
    sources:
        - repoURL: "https://github.com/vvelc/nb-api-proto-infra"
          targetRevision: HEAD
          path: "charts/nb-api-proto"
          helm:
              valueFiles:
                  - values-prod.yaml
        - repoURL: "https://github.com/vvelc/nb-api-proto"
          targetRevision: main
          ref: values
    destination:
        server: "https://kubernetes.default.svc"
        namespace: prod
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
